[package]
name = "sanskritkurs-payer"
version = "1.8.10"
description = "Sanskritkurs — Alois Payer"
authors = ["Alois Payer"]
edition = "2021"

[lib]
name = "sanskritkurs_payer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
