FROM node:20-alpine
WORKDIR /app

# Kopiere package.json und installiere dependencies
COPY author-server/package*.json ./
RUN npm install

# Kopiere den Server Code
COPY author-server/server.js ./

# Kopiere die gebauten VitePress Dateien in den public Ordner des Servers
COPY docs/.vitepress/dist-author ./public

EXPOSE 80
CMD ["npm", "start"]
